config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'posts#index'
  get 'post/search' => 'posts#search'

  resources :users
  resources :posts
  resources :comments
  resources :relationships, only:[:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :contacts, only: [:show, :create, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

	belongs_to :user
	belongs_to :post
	has_many :notifications, dependent: :destroy

	mount_uploader :comment_image, CommentImageUploader
	mount_uploader :comment_video, CommentVideoUploader

	validates :body, presence: true, length: { maximum: 50 }
end

app/models/contact.rb
class Contact < ApplicationRecord

	belongs_to :user
end

app/models/conversation.rb
class Conversation < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user
	belongs_to :post

	validates :user_id, presence: true
	validates :post_id, presence: true
end

app/models/messeage.rb
class Messeage < ApplicationRecord
end

app/models/notification.rb
class Notification < ApplicationRecord
	default_scope -> { order(created_at: :desc) } #新しい通知から受け取るため

	belongs_to :comment, optional: true #optional: trueでnilを許可

	belongs_to :sender, class_name: 'User', foreign_key: 'sender_id', optional: true
  	belongs_to :recipient, class_name: 'User', foreign_key: 'recipient_id', optional: true
end

app/models/post.rb
class Post < ApplicationRecord

	belongs_to :user

	has_many :comments, dependent: :destroy
	has_many :favorite, dependent: :destroy

	mount_uploader :post_image, PostImageUploader
	mount_uploader :post_video, PostVideoUploader

	validates :body, presence: true, length: { maximum: 50 }

	def favorite?(post, user)
		post.favorites.find_by(user_id: user.id)
	end

	def create_notification_by(current_user)
		notification = current_user.active_notifications.new(
			post_id:self.id,
			sender_id:self.contributer.id,
			action:"comment"
			)

			notification.save if notification.valid?
	end

	def create_notification_by(current_user)
		notification = current_user.active_notifications.new(
			post_id:self.id,
			sender_id:self.contributer.id,
			action:"follow"
			)

			notification.save if notification.valid?
	end
end

app/models/relationship.rb
class Relationship < ApplicationRecord

	belongs_to :following, class_name: "User"
	belongs_to :followed, class_name: "User"
	#class_nameで"User"モデルをfollowingとfollowedの二つに分ける

	validates :following_id, presence: true
	validates :followed_id, presence: true
	#_idが空でないことを確認
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :profile_image, ProfileImageUploader
  mount_uploader :back_image, BackImageUploader

  has_many :active_relationships, class_name: "Relationship",
  #一つのモデルから二つのアソシエーション経路を組むときにclass_nameを使いモデルを二つに分けることができる
        foreign_key: "following_id", dependent: :destroy #following_idは自分
  has_many :passive_relationships, class_name: "Relationship",
        foreign_key: "followed_id", dependent: :destroy #followed_idは自分

  has_many :followeds, through: :active_relationships, source: :followed #フォローしているユーザを取り出せるようにしている
  #class_nameで便宜的に"User"モデルを分け(followingとfollowed)、followingテーブルーrelationshioテーブルーfollowedテーブルの形を作り、has_many,thoughを使いfollowingテーブルから直接followedテーブルを定義している
  has_many :followings, through: :passive_relationships, source: :following

  def follow(other_user) #ユーザをフォローする
    self.active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user) #ユーザのフォローを外す
    self.active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user) #フォローしているかどうかを確認する(フォローしていたらtrueを返す)
    followeds.include?(other_user) #followedの中にユーザが含まれているかどうか
  end

  has_many :active_notifications, class_name: "Notification",
        foreign_key: "sender_id", dependent: :destroy
  has_many :passive_notifications, class_name: "notification",
        foreign_key: "recipient_id", dependent: :destroy

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorite, dependent: :destroy
  has_many :contacts, dependent: :destroy

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
    comment=current_user.active_comment.new(post_id:params[:post_id])
    like.save
    @post = Post.find(params[:post_id])
    @post.create_notification_by(current_user)
    respond_to do |format|
      format.html {redirect_to request.referrer}
      format.js
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@posts = Post.all.order(created_at: :desc)
		@all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(15).pluck(:post_id))
	end

	def show
		@post = Post.find(params[:id])
		@comments = @post.comments
		@comment = Comment.new
	end

	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id
		@post.save
	end

	def destory
		@post = Post.find(params[:id])
		@post.destory
		redirect_to user_path(@post.user.id)
	end

	def search
		@posts = Post.where('posts.body like ?', '%' + params[:keyword] + '%').order(created_at: :desc)
		@users = User.where('users.name like ?', '%' + params[:keyword] + '%')
	end

	private
		def post_params
			params.require(:post).permit(:user_id, :body, :post_image, :post_video)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
		@post = Post.new
	end

	def follow
		@user = User.find(params[:id])
		@followings = @user.followings
		@followers = @user.followers
	end

	def create
		@post = Post.new(post_params)
		@post.save
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		@user.update(user_params)
		redirect_to user_path(@user.id)
	end

	def destroy
		@user = User(params[:id])
		@user.destroy
		redirect_to posts_path
	end

	private
		def user_params
			params.require(:user).permit(:name, :introduction, :profile_image, :back_image)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def devise_error_messages
	    return "" if resource.errors.empty?
	    html = ""
	    messages = resource.errors.full_messages.each do |msg|
	      html += <<-EOF
	        <div class="error_field alert alert-danger" role="alert">
	          <p class="error_msg">#{msg}</p>
	        </div>
	      EOF
	    end
	    html.html_safe
  	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/messeages_helper.rb
module MesseagesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_contents.html.erb
<% if user_signed_in? %>
		<%= form_for [@post, @comment] do |f| %>
			<%= f.text_field :body %>
			<%= f.submit 'コメントする' %>
		<% end %>
<% end %>



<%= attachment_image_tag @post.user,:profile_image %>
<%= @post.user.name %>
<%= @post.body %>
<% if @post.post_image.present? %>
	<%= attachment_image_tag @post, :post_image %>
<% end %>
<% if @post.post_video.file.present? %>
	<%= @post.post_video %>
<% end %>

<%= @comments.each do |comment| %>
	<%= attachment_image_tag comment.user,:profile_image %>
	<%= comment.user.name %>
	<%= comment.body %>
	<% if comment.comment_image.present? %>
		<%= attachment_image_tag comment, :comment_image %>
	<% end %>
	<% if comment.comment_video.present? %>
		<%= commet.comment_video %>
	<% end %>
<% end %>



<div id="favorite_btn">
	<%= render template: "favorites/like", post: @post, favorite: @favorite %>
</div>

app/views/posts/_new_post.html.erb
<button id="modal-open">投稿する</button>
	<div id="modal-content">
		<div id="modal-overlay"></div>
		<%= form_for(@post) do |f| %>
			<p class="post-form">
				<%= f.text_area :body %>
			</p>

			<p class="contact-form">
				<%= f.submit "送信する" %>
			</p>
		<% end %>
		<div id="modal-close" style="cursor: pointer">閉じる</div>
	</div>


<script src="js/modal.js"></script>

app/views/posts/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-6 col-offset2">
			<p id="tabcontrol">
			   <a href="#tabpage1">最新の投稿</a>
			   <%# hrefとidの属性値(tabpage1)を一致させページ内リンクとして機能させる %>
			   <a href="#tabpage2">話題の投稿</a>
			   <%# hrefとidの属性値(tabpage2)を一致させページ内リンクとして機能させる %>
			   	<div id="tabbody">
				   <div id="tabpage1">
				   		<% @posts.each do |post| %>
							<%= image_tag post.user.profile_image.url %>
							<%= post.user.name %>
							<%= post.body %>
							<% if post.post_image.present? %>
								<%= image_tag post.post_image.url %>
							<% end %>
							<% if post.post_video.file.present? %>
								<%= post.post_video %>
							<% end %>
						<% end %>
					</div>
				   	<div id="tabpage2">
				   		<%= @all_ranks.each do |post| %>
				   			<%= image_tag post.user.profile_image.url %>
							<%= post.user.name %>
							<%= post.body %>
							<% if post.post_image.present? %>
								<%= image_tag post.post_image.url %>
							<% end %>
							<% if post.post_video.file.present? %>
								<%= post.post_video %>
							<% end %>
				   		<% end %>
				   	</div>
				</div>
			</p>
		</div>
		<div class="col-2">
			<p>人気のユーザー</p>
		</div>
	</div>
</div>

<script type="text/javascript">
	var tabs = document.getElementById('tabcontrol').getElementsByTagName('a');
	var pages = document.getElementById('tabbody').getElementsByTagName('div');

	function changeTab() {
		var targetid = this.href.substring(this.href.indexOf('#')+1,this.href.length);
		for(var i=0; i<pages.length; i++) {
	      if( pages[i].id != targetid ) {
	         pages[i].style.display = "none";
	      }
	      else {
	         pages[i].style.display = "block";
	      }
	    }

	    for(var i=0; i<tabs.length; i++) {
      		tabs[i].style.zIndex = "0";
		}
		this.style.zIndex = "10";

		return false;
		}

		for(var i=0; i<tabs.length; i++) {
   			tabs[i].onclick = changeTab;
		}

		tabs[0].onclick();
</script>

app/views/posts/search.html.erb
<%= params[:keyword] %>の検索結果
<% @posts.each do |post| %>
	<%= image_tag post.user.profile_image.url %>
	<%= post.user.name %>
	<%= post.name %>
	<% if post.post_image.present? %>
		<%= image_tag post.post_image.url %>
	<% end %>
	<% if post.post_video.file.present? %>
		<%= post.post_video %>
	<% end %>
<% end %>
<% @users.each do |user| %>
	<% user.name %>
<% end %>

app/views/posts/show.html.erb
<div class="container">
	<% if user_signed_in? %>
		<%= form_for [@post, @comment] do |f| %>
			<%= f.text_field :body %>
			<%= f.submit 'コメントする' %>
		<% end %>
	<% end %>
	<div class="row">
		<div class="col-6 col-offset-2">
			<%= image_tag @post.user.profile_image.url %>
			<%= @post.user.name %>
			<%= @post.body %>
			<% if @post.post_image.present? %>
				<%= image_tag @post.post_image.url %>
			<% end %>
			<% if @post.post_video.file.present? %>
				<%= @post.post_video %>
			<% end %>

			<%= @comments.each do |comment| %>
				<%= image_tag comment.user.profile_image.url %>
				<%= comment.user.name %>
				<%= comment.body %>
				<% if comment.comment_image.present? %>
					<%= image_tag comment.comment_image.url %>
				<% end %>
				<% if comment.comment_video.present? %>
					<%= commet.comment_video %>
				<% end %>
			<% end %>
		</div>
		<div class="col-2">
			人気のユーザ
		</div>
	</div>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/index.html.erb
 <% @users.each do |user| %>
 	<%= user.name %>
	 <% if current_user != user %>
		  <div id="follow_form">
		  <% if current_user.following?(user) %>
		    <%= render 'unfollow', user: user %>
		  <% else %>
		    <%= render 'follow', user: user %>
		  <% end %>
		  </div>
	<% end %>
<% end %>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-3">
			<%= link_to user_path(current_user) do %>
					<li>ホーム</li>
			<% end %>
			<li>通知</li>
			<li>メッセージ</li>
			<%= link_to contacts_path do %>
					<li>お問い合わせ</li>
			<% end %>
			<li><%= link_to edit_user_path(current_user) do %>
					プロフィール
				<% end %>
			</li>
			<li>投稿</li>
		</div>
		<div class="col-6">
			<div class="row">
				<div class="col-12">
					<%= @user.name %>
				</div>
				<div class="col-12">
					<div class="new">
						<%= form_for(@post) do |f| %>
							<%= f.text_area :body %>
							<%= f.file_field :post_image %>
							<%= f.file_field :post_video %>
							<%= f.submit '投稿する' %>
						<% end %>
					</div>
				</div>
				<div class="col-12">
					自分がフォローしている人の投稿一覧
				</div>
			</div>
		</div>
		<div class="col-3">
			<div class="row">
				<div class="col-8 offset-4">
					<p>HOT ユーザー</p>
				</div>
				<div class="col-7 offset-5">
					<p>一週間で最もフォローされたユーザ５人</p>
				<div>
				<div class="col-8 offset-4">
					<p>おすすめユーザー</p>
				</div>
				<div class="col-7 offset-5">
					<p>自分がフォローしているユーザーがフォローしているユーザー</p>
				</div>
			</div>
		</div>
	</div>
</div>